language: node_js

node_js:
  # latest stable release
  - node
  # latest LTS release
  - lts/*

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn type-check
  - yarn lint

deploy:
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: oZMA/bt4DSzuvfBTDVIWoaBPbtUEr+7y4qK01M5ZVMn9Y2pG8PONAR5XgKe56aEeXDfa6YPZBTZ1Z8oJk0js7nDOt4KeJ2twIXLCOBoNuSfTFC7PSHPOfzKIb04e8rvFiiWfh0QPkd2TSF4v0QZo/Nh2SjvyPslOfsUNrsrnwJiTnhZKCO9IFSogJdG+ktj5t3Apu1bxiZnnGExOwgETcHR6+IE/qg7Ly2imKV9TQYVw40BFfZQVbBkvlboeJ9LCXfeGl3AR7BBVrfItkXLuN311PJf1nq+oBZqQ8g4826FAHjc9UW3C6JEpZPvSO5iKXn13sZoMaR5pmGse1Xz1muB2CsBW2crVp/lslNnZvkgTFCSh27LzRrnZUxgwhqC8fGKZhE3W/VH2bRxRX3QGZgv0YX/fkKpGAYn/2+Z+YL6w6pquC+2lxhS1vzYqRJPN0CDrzjOoEfGTx/ODrL3C8YPh3rZLT9utMigPM+ZHx2cFkxKiv6V+OMafMKT7+yu50jUSNQLJL+I/YcNiPm7DPx8udUHDSG1iIVCpoWSHZAJuvybE8fGhyuoTMdcsoXoGzqKJiX7UtiKUBcVVdqLLW4rnAfFKTu6nsJqizLHnqvN+Z/rr/NimrsimLm7xcZ3oIOrmBpEfAKDPltgzSwAKUshUrb3Wgyt+ZXRGY6wdE5o=
    on:
      tags: true
